docs: fix docs.rs build
The current documentation build in docs.rs breaks with the following
error:

    [INFO] [stderr] error[E0557]: feature has been removed
    [INFO] [stderr]   --> src/lib.rs:11:29
    [INFO] [stderr]    |
    [INFO] [stderr] 11 | #![cfg_attr(docsrs, feature(doc_auto_cfg))]
    [INFO] [stderr]    |                             ^^^^^^^^^^^^ feature has been removed
    [INFO] [stderr]    |
    [INFO] [stderr]    = note: removed in 1.92.0; see <https://github.com/rust-lang/rust/pull/138907> for more information
    [INFO] [stderr]    = note: merged into `doc_cfg`

So replace `doc_auto_cfg` with `doc_cfg`, which generates the expected
docs, showing the required features for each module.

Signed-off-by: Carlos López <carlos.lopezr4096@gmail.com>